config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'pages#home'

  get '/bonjour(/:name)', to: 'pages#salut', as: 'salut'

  resources :posts

  resources :categories

end

app/models/Post.rb
class Post < ApplicationRecord

  include Sluggable

  default_scope { order(created_at: :desc) }
  scope :online, -> (online = 1) { where(online: online) }

  def as_json(options = nil)
    super(only: [:id, :name, :created_at])
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  include Sluggable

  validates :name, on: [:create, :update], presence: true

  has_many :posts
  has_many :metas, as: :metaable

end

app/models/concerns/sluggable.rb
module Sluggable

  extend ActiveSupport::Concern

  included do
    before_validation :set_default_slug, on: [:create, :update]
    validates :slug, on: [:create, :update], format: { with: /\A[a-z0-9\-]+\z/ }, uniqueness: true

    private

    def set_default_slug
      if !self.slug.nil? && !self.name.nil? && !self.name.empty? && self.slug.empty?
        self.slug = name.parameterize
      elsif !self.slug.nil? && !self.slug.empty?
        self.slug = self.slug.parameterize
      end
    end
  end

end

app/models/meta.rb
class Meta < ApplicationRecord

  belongs_to :metaable, polymorphic: true

end

app/models/post.rb
class Post < ApplicationRecord

  include Sluggable

  validates :name, on: [:create, :update], presence: true

  belongs_to :category, counter_cache: true
  has_and_belongs_to_many :tags
  has_many :metas, as: :metaable

  scope :online, -> (online = 1) { where(online: online) }

  def as_json(options = nil)
    super(only: [:id, :name, :created_at])
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all

    respond_to do |format|
      format.html
      format.json { render json: @categories }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @category }
    end
  end

  def edit
  end

  def update
    if @category.update category_params
      redirect_to categories_path, flash: { success: "Catégorie modifiée avec succès" }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, flash: { success: "Catégorie supprimée avec succès" }
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create category_params
    if !@category.errors.any?
      redirect_to category_path(@category.id), flash: { success: "Catégorie créée avec succès" }
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end

  def set_category
    @category = Category.find params[:id]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def salut
    @name = params[:name]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.includes(:category, :tags).all

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to posts_path, flash: { success: "Article modifié avec succès" }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create post_params
    if !@post.errors.any?
      redirect_to post_path(@post.id), flash: { success: "Article créé avec succès" }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, flash: { success: "Article supprimé avec succès" }
  end

  private

  def post_params
    params.require(:post).permit(:name, :content, :slug, :category_id)
  end

  def set_post
    @post = Post.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gravatar_helper.rb
module GravatarHelper

  def gravatar(email, options = { s: 200 })
    throw TypeError unless email.respond_to? :to_s
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.to_s)}?s=#{options[:s]}", alt: "pfp"
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<h1>Éditer la catégorie</h1>

<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_for @category do |f| %>

  <div class="mb-3">
    <label class="form-label">Titre de la catégorie</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <label class="form-label">URL de la catégorie</label>
    <%= f.text_field :slug, class: "form-control" %>
  </div>

  <button type="submit" class="btn btn-success">Mettre à jour la catégorie</button>

<% end %>

app/views/categories/index.html.erb
<h1>Catégories</h1>

<table class="table">
  <thead>
  <tr>
    <td>ID</td>
    <td>Nom</td>
    <td>Actions</td>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= category.name %></td>
      <td class="d-flex gap-1">
        <%= button_to "Détails", category_path(category.id), method: :get, class: "btn btn-primary" %>
        <%= button_to "Éditer", edit_category_path(category.id), method: :get, class: "btn btn-success" %>
        <%= button_to "Supprimer", category, method: :delete, form: { data: { turbo_confirm: "Êtes-vous sûr ?" } }, class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
  <a href="<%= new_category_path %>" class="btn btn-success">Créer une nouvelle catégorie</a>
</p>

app/views/categories/new.html.erb
<h1>Créer une nouvelle catégorie</h1>

<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_for @category do |f| %>

  <div class="mb-3">
    <label class="form-label">Nom de la catégorie</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <label class="form-label">URL de la catégorie</label>
    <%= f.text_field :slug, class: "form-control" %>
  </div>

  <button type="submit" class="btn btn-success">Créer la catégorie</button>

<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p><%= @category.slug %></p>

<p>
  <a href="<%= categories_path %>" class="btn btn-primary">Retour aux catégories</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title><%= content_for?(:title) ? yield(:title) : "RoR-Formation" %></title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>


  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</head>

<body>
<div class="container" style="margin-top: 5rem;">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>"><%= msg %></div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/layouts/sidebar.html.erb
<div class="row">
  <% if content_for? :sidebar %>
    <div class="col-sm-8">
      <%= yield :content %>
    </div>

    <div class="col-sm-4">
      <%= yield :sidebar %>
    </div>
  <% else %>
    <div class="col-sm-12">
      <%= yield :content %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Page d'accueil</h1>

<%= gravatar("contact@natchi.dev") %>

app/views/pages/salut.html.erb
Salut <%= @name %> comment tu vas ?

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <% post.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>
<% end %>

<%= form_for post do |f| %>

  <div class="mb-3">
    <label class="form-label">Titre de l'article</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <label class="form-label">URL de l'article</label>
    <%= f.text_field :slug, class: "form-control" %>
  </div>

  <div class="mb-3">
    <label class="form-label">Catégorie</label>
    <%= f.select :category_id, Category.pluck(:name, :id), {}, class: "form-select" %>
  </div>

  <div class="mb-3">
    <label class="form-label">Contenu de l'article</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <button type="submit" class="btn btn-success">Mettre à jour l'article</button>

<% end %>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.id %></td>
  <td><%= post.name %></td>
  <td><%= post.content %></td>
  <td><%= post.category.name %></td>
  <td>
    <%= post.tags.map(&:name).join(", ") %>
  </td>
  <td class="d-flex gap-1">
    <%= link_to "Détails", post, class: "btn btn-primary" %>
    <%= link_to "Éditer", edit_post_path(post), class: "btn btn-success" %>
    <%= button_to "Supprimer", post, method: :delete, form: { data: { turbo_confirm: "Êtes-vous sûr ?" } }, class: "btn btn-danger" %>
  </td>
</tr>

app/views/posts/edit.html.erb
<h1>Éditer l'article</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Articles du blog</h1>

<table class="table">
  <thead>
  <tr>
    <td>ID</td>
    <td>Nom</td>
    <td>Contenu</td>
    <td>Catégorie</td>
    <td>Tags</td>
    <td>Actions</td>
  </tr>
  </thead>

  <tbody>
  <%= render @posts %>
  </tbody>
</table>

<p>
  <a href="<%= new_post_path %>" class="btn btn-success">Créer un nouvel article</a>
</p>

app/views/posts/new.html.erb
<h1>Créer un nouvel article</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% content_for :title, @post.name %>

<% content_for :content do %>
  <h1><%= @post.name %></h1>

  <p><%= @post.content %></p>

  <p>
    <a href="<%= posts_path %>" class="btn btn-primary">Retour aux articles</a>
  </p>
<% end %>

<% content_for :sidebar do %>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur cupiditate eligendi illo iure mollitia nisi nostrum, officia quaerat quam quisquam sapiente sit ut velit! Adipisci aliquid aspernatur assumenda consectetur culpa delectus distinctio dolore doloremque dolores earum eius enim eos error esse explicabo id itaque, iusto laborum magni nesciunt nihil non nulla odio placeat quae quod quos, rem similique sit tempore velit veniam vero voluptas? Atque aut autem, cupiditate delectus dolorem doloribus eius facere iusto, nemo nesciunt omnis qui ratione repudiandae! A ad aperiam assumenda atque cum dolore ducimus earum eveniet expedita id, minus molestias nemo nisi quaerat quia quod voluptate?
<% end %>

<%= render template: 'layouts/sidebar' %>